import React from 'react';
import { Link } from 'react-router-dom';
import '../css/AllCalculators.css';

// Routes that are live in the app
const LIVE = {
  mortgage: '/mortgage',
  autoLoan: '/auto-loan',
  payment: '/payment',
  amortization: '/amortization',
  incomeTax: '/income-tax',
  interestRate: '/interest',
  interest: '/interest',
  loan: '/loan',
  retirement: '/retirement',
  investment: '/investment',
  inflation: '/inflation',
  personalLoan: '/personal-loan',
  studentLoan: '/student-loan',
  businessLoan: '/business-loan',
  boatLoan: '/boat-loan',
  autoLease: '/auto-lease',
  lease: '/lease',
  vaMortgage: '/va-mortgage',
  fhaLoan: '/fha-loan',
  heloc: '/heloc',
  homeEquityLoan: '/home-equity-loan',
  mortgagePayoff: '/mortgage-payoff',
  refinance: '/refinance',
  downPayment: '/down-payment',
  bmi: '/bmi',
  bodyFat: '/body-fat',
  pregnancy: '/pregnancy',
  pace: '/pace',
  calorie: '/calories',
  bmr: '/bmr',
  idealWeight: '/ideal-weight',
  macro: '/macro',
  tdee: '/tdee',
  leanBodyMass: '/lean-body-mass',
  bodySurfaceArea: '/body-surface-area',
  healthyWeight: '/healthy-weight',
  bodyType: '/body-type',
  armyBodyFat: '/army-body-fat',
  pregnancyConception: '/pregnancy-conception',
  pregnancyWeightGain: '/pregnancy-weight-gain',
  ovulation: '/ovulation',
  period: '/period',
  conception: '/conception',
  oneRepMax: '/one-rep-max',
  protein: '/protein',
  carbohydrate: '/carbohydrate',
  caloriesBurned: '/calories-burned',
  targetHeartRate: '/target-heart-rate',
  fatIntake: '/fat-intake',
  gfr: '/gfr',
  bac: '/bac',
  dueDate: '/due-date',
  scientific: '/scientific',
  percentage: '/percentage',
  randomNumber: '/random-number-generator',
  fraction: '/fraction',
  triangle: '/triangle-calculator',
  stdDev: '/std-dev',
  rounding: '/rounding',
  root: '/root',
  exponent: '/exponent',
  log: '/log',
  hex: '/hex',
  binary: '/binary',
  bigNumber: '/big-number',
  scientificNotation: '/scientific-notation',
  numberSequence: '/number-sequence',
  volume: '/volume',
  area: '/area',
  circle: '/circle',
  surfaceArea: '/surface-area',
  rightTriangle: '/right-triangle',
  pythagorean: '/pythagorean-theorem',
  slope: '/slope',
  distance: '/distance',
  ratio: '/ratio',
  age: '/age',
  time: '/time',
  gpa: '/gpa-calculator',
  ipSubnet: '/ip-subnet-calculator',
  password: '/password',
  conversion: '/conversion',
  date: '/date',
  hours: '/hours-calculator',
  grade: '/grade-calculator',
  concrete: '/concrete-calculator',
  salary: '/salary',
  socialSecurity: '/social-security',
  estateTax: '/estate-tax',
  salesTax: '/sales-tax',
  vat: '/vat',
  marriageTax: '/marriage-tax',
  takeHomePay: '/take-home-pay',
  compoundInterest: '/compound-interest',
  savings: '/savings',
  calc401k: '/401k',
  rothIRA: '/roth-ira',
  ira: '/ira',
  cd: '/cd',
  mutualFund: '/mutual-fund',
  bond: '/bond',
  annuity: '/annuity',
  annuityPayout: '/annuity-payout',
  pension: '/pension',
  rmd: '/rmd',
  averageReturn: '/average-return',
  roi: '/roi',
  irr: '/irr',
  apr: '/apr',
  finance: '/finance',
  currency: '/currency',
  budget: '/budget',
  houseAffordability: '/house-affordability',
  rent: '/rent',
  rentVsBuy: '/rent-vs-buy',
  rentalProperty: '/rental-property',
  realEstate: '/real-estate',
  presentValue: '/present-value',
  futureValue: '/future-value',
  discount: '/discount',
  depreciation: '/depreciation',
  margin: '/margin',
  cashBack: '/cash-back',
  creditCardPayoff: '/credit-card-payoff',
  creditCard: '/credit-card',
  debtConsolidation: '/debt-consolidation',
  debtPayoff: '/debt-payoff',
  repayment: '/repayment',
  debtRatio: '/debt-ratio',
  collegeCost: '/college-cost',
  paybackPeriod: '/payback-period',
};

const CS = '/coming-soon'; // placeholder for unbuilt calculators

const categories = [
  {
    title: 'Financial Calculators',
    items: [
      { label: 'Mortgage Calculator',              to: LIVE.mortgage },
      { label: 'Auto Loan Calculator',             to: LIVE.autoLoan },
      { label: 'Payment Calculator',               to: LIVE.payment },
      { label: 'Amortization Calculator',          to: LIVE.amortization },
      { label: 'Loan Calculator',                  to: LIVE.loan },
      { label: 'Interest Calculator',              to: LIVE.interest },
      { label: 'Income Tax Calculator',            to: LIVE.incomeTax },
      { label: 'Retirement Calculator',            to: LIVE.retirement },
      { label: 'Investment Calculator',            to: LIVE.investment },
      { label: 'Inflation Calculator',             to: LIVE.inflation },
      { label: 'Currency Calculator',              to: LIVE.currency },
      { label: 'Finance Calculator',               to: LIVE.finance },
      { label: 'Salary Calculator',                to: LIVE.salary },
      { label: 'Interest Rate Calculator',         to: LIVE.interestRate },
      { label: 'House Affordability Calculator',   to: LIVE.houseAffordability },
      { label: 'Rent Calculator',                  to: LIVE.rent },
      { label: 'Estate Tax Calculator',            to: LIVE.estateTax },
      { label: 'Social Security Calculator',       to: LIVE.socialSecurity },
      { label: 'Annuity Payout Calculator',        to: LIVE.annuityPayout },
      { label: 'Credit Cards Payoff Calculator',   to: LIVE.creditCardPayoff },
      { label: 'Debt Consolidation Calculator',    to: LIVE.debtConsolidation },
      { label: 'Student Loan Calculator',          to: LIVE.studentLoan },
      { label: 'Simple Interest Calculator',       to: LIVE.interest },
      { label: 'Bond Calculator',                  to: LIVE.bond },
      { label: 'Roth IRA Calculator',              to: LIVE.rothIRA },
      { label: 'RMD Calculator',                   to: LIVE.rmd },
      { label: 'Cash Back or Low Interest Calculator', to: LIVE.cashBack },
      { label: 'Depreciation Calculator',          to: LIVE.depreciation },
      { label: 'Margin Calculator',                to: LIVE.margin },
      { label: 'Business Loan Calculator',         to: LIVE.businessLoan },
      { label: 'Real Estate Calculator',           to: LIVE.realEstate },
      { label: 'Personal Loan Calculator',         to: LIVE.personalLoan },
      { label: 'Lease Calculator',                 to: LIVE.lease },
      { label: 'Budget Calculator',                to: LIVE.budget },
      { label: 'IRR Calculator',                   to: LIVE.irr },
      { label: 'APR Calculator',                   to: LIVE.apr },
      { label: 'VA Mortgage Calculator',           to: LIVE.vaMortgage },
      { label: 'HELOC Calculator',                 to: LIVE.heloc },
      { label: 'Rent vs. Buy Calculator',          to: LIVE.rentVsBuy },
      { label: 'Present Value Calculator',         to: LIVE.presentValue },
      { label: 'Future Value Calculator',          to: LIVE.futureValue },
      { label: 'Mortgage Payoff Calculator',       to: LIVE.mortgagePayoff },
      { label: 'Compound Interest Calculator',     to: LIVE.compoundInterest },
      { label: '401K Calculator',                  to: LIVE.calc401k },
      { label: 'Sales Tax Calculator',             to: LIVE.salesTax },
      { label: 'Savings Calculator',               to: LIVE.savings },
      { label: 'Marriage Tax Calculator',          to: LIVE.marriageTax },
      { label: 'Pension Calculator',               to: LIVE.pension },
      { label: 'Annuity Calculator',               to: LIVE.annuity },
      { label: 'Credit Card Calculator',           to: LIVE.creditCard },
      { label: 'Debt Payoff Calculator',           to: LIVE.debtPayoff },
      { label: 'Repayment Calculator',             to: LIVE.repayment },
      { label: 'College Cost Calculator',          to: LIVE.collegeCost },
      { label: 'CD Calculator',                    to: LIVE.cd },
      { label: 'Mutual Fund Calculator',           to: LIVE.mutualFund },
      { label: 'IRA Calculator',                   to: LIVE.ira },
      { label: 'VAT Calculator',                   to: LIVE.vat },
      { label: 'Auto Lease Calculator',            to: LIVE.autoLease },
      { label: 'Average Return Calculator',        to: LIVE.averageReturn },
      { label: 'Discount Calculator',              to: LIVE.discount },
      { label: 'Debt-to-Income Ratio Calculator',  to: LIVE.debtRatio },
      { label: 'Take-Home-Paycheck Calculator',    to: LIVE.takeHomePay },
      { label: 'Boat Loan Calculator',             to: LIVE.boatLoan },
      { label: 'Refinance Calculator',             to: LIVE.refinance },
      { label: 'Rental Property Calculator',       to: LIVE.rentalProperty },
      { label: 'ROI Calculator',                   to: LIVE.roi },
      { label: 'FHA Loan Calculator',              to: LIVE.fhaLoan },
      { label: 'Home Equity Loan Calculator',      to: LIVE.homeEquityLoan },
      { label: 'Down Payment Calculator',          to: LIVE.downPayment },
      { label: 'Payback Period Calculator',        to: LIVE.paybackPeriod },
    ],
  },
  {
    title: 'Fitness & Health Calculators',
    items: [
      { label: 'BMI Calculator',                   to: LIVE.bmi },
      { label: 'Body Fat Calculator',              to: LIVE.bodyFat },
      { label: 'Calorie Calculator',               to: LIVE.calorie },
      { label: 'BMR Calculator',                   to: LIVE.bmr },
      { label: 'Ideal Weight Calculator',          to: LIVE.idealWeight },
      { label: 'Due Date Calculator',              to: LIVE.dueDate },
      { label: 'Pregnancy Calculator',             to: LIVE.pregnancy },
      { label: 'Pace Calculator',                  to: LIVE.pace },
      { label: 'Macro Calculator',                 to: LIVE.macro },
      { label: 'TDEE Calculator',                  to: LIVE.tdee },
      { label: 'Healthy Weight Calculator',        to: LIVE.healthyWeight },
      { label: 'Lean Body Mass Calculator',        to: LIVE.leanBodyMass },
      { label: 'Body Surface Area Calculator',     to: LIVE.bodySurfaceArea },
      { label: 'Army Body Fat Calculator',         to: LIVE.armyBodyFat },
      { label: 'Body Type Calculator',             to: LIVE.bodyType },
      { label: 'Pregnancy Conception Calculator',  to: LIVE.pregnancyConception },
      { label: 'Pregnancy Weight Gain Calculator', to: LIVE.pregnancyWeightGain },
      { label: 'Conception Calculator',            to: LIVE.conception },
      { label: 'Ovulation Calculator',             to: LIVE.ovulation },
      { label: 'Period Calculator',                to: LIVE.period },
      { label: 'One Rep Max Calculator',           to: LIVE.oneRepMax },
      { label: 'Protein Calculator',               to: LIVE.protein },
      { label: 'Carbohydrate Calculator',          to: LIVE.carbohydrate },
      { label: 'Calories Burned Calculator',       to: LIVE.caloriesBurned },
      { label: 'Target Heart Rate Calculator',     to: LIVE.targetHeartRate },
      { label: 'Fat Intake Calculator',            to: LIVE.fatIntake },
      { label: 'GFR Calculator',                   to: LIVE.gfr },
      { label: 'BAC Calculator',                   to: LIVE.bac },
    ],
  },
  {
    title: 'Math Calculators',
    items: [
      { label: 'Scientific Calculator',            to: LIVE.scientific },
      { label: 'Percentage Calculator',            to: LIVE.percentage },
      { label: 'Fraction Calculator',              to: LIVE.fraction },
      { label: 'Triangle Calculator',              to: LIVE.triangle },
      { label: 'Standard Deviation Calculator',    to: LIVE.stdDev },
      { label: 'Random Number Generator',          to: LIVE.randomNumber },
      { label: 'Rounding Calculator',              to: LIVE.rounding },
      { label: 'Root Calculator',                  to: LIVE.root },
      { label: 'Exponent Calculator',              to: LIVE.exponent },
      { label: 'Log Calculator',                   to: LIVE.log },
      { label: 'Hex Calculator',                   to: LIVE.hex },
      { label: 'Binary Calculator',                to: LIVE.binary },
      { label: 'Big Number Calculator',            to: LIVE.bigNumber },
      { label: 'Scientific Notation Calculator',   to: LIVE.scientificNotation },
      { label: 'Number Sequence Calculator',       to: LIVE.numberSequence },
      { label: 'Volume Calculator',                to: LIVE.volume },
      { label: 'Area Calculator',                  to: LIVE.area },
      { label: 'Circle Calculator',                to: LIVE.circle },
      { label: 'Surface Area Calculator',          to: LIVE.surfaceArea },
      { label: 'Right Triangle Calculator',        to: LIVE.rightTriangle },
      { label: 'Pythagorean Theorem Calculator',   to: LIVE.pythagorean },
      { label: 'Slope Calculator',                 to: LIVE.slope },
      { label: 'Distance Calculator',              to: LIVE.distance },
      { label: 'Ratio Calculator',                 to: LIVE.ratio },
      { label: 'Percent Error Calculator',         to: CS },
      { label: 'Half-Life Calculator',             to: CS },
      { label: 'Probability Calculator',           to: CS },
      { label: 'Mean Median Mode Range Calculator',to: CS },
      { label: 'Z-score Calculator',               to: CS },
      { label: 'Greatest Common Factor Calculator',to: CS },
      { label: 'Prime Factorization Calculator',   to: CS },
      { label: 'Quadratic Formula Calculator',     to: CS },
      { label: 'Sample Size Calculator',           to: CS },
      { label: 'Statistics Calculator',            to: CS },
      { label: 'Permutation and Combination Calculator', to: CS },
      { label: 'Confidence Interval Calculator',   to: CS },
      { label: 'Least Common Multiple Calculator', to: CS },
      { label: 'Factor Calculator',                to: CS },
      { label: 'Matrix Calculator',                to: CS },
      { label: 'Common Factor Calculator',         to: CS },
      { label: 'P-value Calculator',               to: CS },
    ],
  },
  {
    title: 'Other Calculators',
    items: [
      { label: 'Age Calculator',                   to: LIVE.age },
      { label: 'Time Calculator',                  to: LIVE.time },
      { label: 'GPA Calculator',                   to: LIVE.gpa },
      { label: 'IP Subnet Calculator',             to: LIVE.ipSubnet },
      { label: 'Password Generator',               to: LIVE.password },
      { label: 'Conversion Calculator',            to: LIVE.conversion },
      { label: 'Date Calculator',                  to: LIVE.date },
      { label: 'Hours Calculator',                 to: LIVE.hours },
      { label: 'Grade Calculator',                 to: LIVE.grade },
      { label: 'Concrete Calculator',              to: LIVE.concrete },
      { label: 'Height Calculator',                to: CS },
      { label: 'Voltage Drop Calculator',          to: CS },
      { label: 'Square Footage Calculator',        to: CS },
      { label: 'Time Zone Calculator',             to: CS },
      { label: 'GDP Calculator',                   to: CS },
      { label: 'Horsepower Calculator',            to: CS },
      { label: 'Stair Calculator',                 to: CS },
      { label: 'Ohms Law Calculator',              to: CS },
      { label: 'Shoe Size Conversion',             to: CS },
      { label: 'Mileage Calculator',               to: CS },
      { label: 'Mass Calculator',                  to: CS },
      { label: 'Speed Calculator',                 to: CS },
      { label: 'Molecular Weight Calculator',      to: CS },
      { label: 'Golf Handicap Calculator',         to: CS },
      { label: 'Tire Size Calculator',             to: CS },
      { label: 'Tile Calculator',                  to: CS },
      { label: 'Gravel Calculator',                to: CS },
      { label: 'Heat Index Calculator',            to: CS },
      { label: 'Bandwidth Calculator',             to: CS },
      { label: 'URL Encode / Decode',              to: CS },
      { label: 'Day Counter',                      to: CS },
      { label: 'Bra Size Calculator',              to: CS },
      { label: 'Dice Roller',                      to: CS },
      { label: 'Fuel Cost Calculator',             to: CS },
      { label: 'BTU Calculator',                   to: CS },
      { label: 'Time Card Calculator',             to: CS },
      { label: 'Love Calculator',                  to: CS },
      { label: 'Gas Mileage Calculator',           to: CS },
      { label: 'Engine Horsepower Calculator',     to: CS },
      { label: 'Resistor Calculator',              to: CS },
      { label: 'Electricity Calculator',           to: CS },
      { label: 'Tip Calculator',                   to: CS },
      { label: 'Density Calculator',               to: CS },
      { label: 'Weight Calculator',                to: CS },
      { label: 'Molarity Calculator',              to: CS },
      { label: 'Roman Numeral Converter',          to: CS },
      { label: 'Sleep Calculator',                 to: CS },
      { label: 'Roofing Calculator',               to: CS },
      { label: 'Mulch Calculator',                 to: CS },
      { label: 'Wind Chill Calculator',            to: CS },
      { label: 'Dew Point Calculator',             to: CS },
      { label: 'Base64 Encode / Decode',           to: CS },
      { label: 'Time Duration Calculator',         to: CS },
      { label: 'Day of the Week Calculator',       to: CS },
    ],
  },
  {
    title: 'Calculators for Your Site',
    items: [
      { label: 'Mortgage Calculator for Your Site',   to: CS },
      { label: 'Scientific Calculator for Your Site', to: CS },
      { label: 'Concrete Calculator for Your Site',   to: CS },
      { label: 'Math Calculator for Your Site',       to: CS },
      { label: 'Love Calculator for Your Site',       to: CS },
    ],
  },
];

const footerLinks = [
  { label: 'Home Page',      to: '/' },
  { label: 'About Us',       to: CS },
  { label: 'Privacy Policy', to: CS },
  { label: 'Terms of Use',   to: CS },
];

export default function AllCalculators() {
  return (
    <div className="all-calc-container">
      {/* Breadcrumb */}
      <nav className="all-calc-breadcrumb" aria-label="breadcrumb">
        <Link to="/">Home</Link>
        <span className="sep">/</span>
        <span>All Calculators</span>
      </nav>

      <h1 className="all-calc-heading">All Calculators</h1>

      <div className="all-calc-sections">
        {categories.map((cat) => (
          <section key={cat.title} className="all-calc-section">
            <h2 className="all-calc-section-title">{cat.title}</h2>
            <ul className="all-calc-links">
              {cat.items.map((item) => (
                <li key={item.label}>
                  <Link
                    to={item.to}
                    className={item.to === CS ? 'link-soon' : ''}
                    title={item.to === CS ? 'Coming soon' : undefined}
                  >
                    {item.label}
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </div>

      {/* Footer links */}
      <div className="all-calc-footer">
        {footerLinks.map((fl) => (
          <Link key={fl.label} to={fl.to}>
            {fl.label}
          </Link>
        ))}
      </div>
    </div>
  );
}
